// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCheatSheet(arg1) {
  return window['go']['main']['App']['GetCheatSheet'](arg1);
}

export function GetPrograms() {
  return window['go']['main']['App']['GetPrograms']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
