// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCheatSheet(arg1:string):Promise<string>;

export function GetPrograms():Promise<string>;

export function GetVersion():Promise<string>;
