name: Release Chsht

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: DesktopCheatSheet, platform: windows/amd64, os: windows-latest},
          {name: DesktopCheatSheet, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          nsis: true
          go-version: 1.24
          wails-build-webview2: embed